README.md, src/components/Adyen/Adyen.js, src/util/appConfigHelper.js
- Config.setAdyenConfig was added
=> Add adyen configuration method

src/components/Adyen/Adyen.js, src/components/Adyen/Adyen.spec.js
- Card holder name input was added
=> Add cardholder input in Adyen component

src/util/planHelper.js
Add Australian dollar currency code to `currencyFormat` function.
=> Add Australian Dollar to currencyFormat util

README.md, src/components/InnerPopupWrapper/InnerPopupWrapperStyled.js, src/components/UpdatePaymentDetailsPopup/Steps/AddCard.js, src/components/UpdatePaymentDetailsPopup/Steps/AddPayPal.js
- update documentation for availablePaymentMethods
- add a warning message when the user wants to update payment details
=> Payment method change warning

README.md, src/api/Payment/submitPayPalPayment.js, src/api/PaymentDetails/updatePayPalPaymentDetails.js, src/components/UpdatePaymentDetailsPopup/Steps/AddCard.js, src/components/UpdatePaymentDetailsPopup/Steps/AddPayPal.js, src/components/UpdatePaymentDetailsPopup/UpdatePaymentDetailsPopup.js, src/containers/MyAccount/MyAccount.component.js, src/services/__tests__/auth.spec.js, src/services/auth.js, src/util/appConfigHelper.js
- Rename setPaypalUrls to setCheckoutPayPalUrls
- Add setMyAccountPayPalUrls
- Update documentation for Checkout, Purchase, MyAccount and PaymentInfo
- When new payment details are added the old ones don’t need to be deleted
=> PayPal improvements

src/components/Adyen/Adyen.js, src/translations/en/translations.json, src/translations/pl/translations.json
=> Change update payment confirm button text

src/api/Customer/updateSwitch.js, src/api/index.js, src/components/CancelSwitchPopup/CancelSwitchPopup.js, src/components/CancelSwitchPopup/index.js, src/components/CurrentPlan/CurrentPlan.js, src/components/OfferCard/OfferCard.js, src/containers/PlanDetails/PlanDetails.component.js, src/containers/PlanDetails/PlanDetails.container.js, src/redux/innerPopupReducer.js, src/redux/planDetails.js, src/translations/en/translations.json, src/translations/pl/translations.json
=> Cancel switch

.github/workflows/release.yml
I'm adding a force to try to fix the last step of release workflow. I also upgraded Paweł's permissions, so hopefully this should be enough.
=> Try to fix release workflow

src/components/Input/Input.js, src/components/Input/Input.test.js, src/components/Input/InputStyled.js
- Refactor Input component
- Add tests
=> Refactor Input component

src/components/Adyen/AdyenStyled.js, src/components/Payment/DropInSection/DropInSectionStyled.js
=> change radiobutton color to green

src/components/MyAccountError/MyAccountError.js, src/components/MyAccountError/MyAccountErrorStyled.js, src/components/PaymentMethod/PaymentMethod.js
=> Align style of the add payment details section

src/components/CurrentPlan/CurrentPlan.js, src/components/SubscriptionIcon/SubscriptionIconStyled.js, src/components/SubscriptionManagement/SubscriptionManagement.js, src/components/SubscriptionManagement/SubscriptionManagementStyled.js, src/translations/en/translations.json
=> Add paused subscription state

src/components/ResumeSubscriptionPopup/ResumeSubscriptionPopup.js, src/components/ResumeSubscriptionPopup/ResumeSubscriptionPopupStyled.js, src/components/ResumeSubscriptionPopup/index.js, src/components/SubscriptionIcon/SubscriptionIconStyled.js, src/components/SubscriptionManagement/SubscriptionManagement.js, src/components/SubscriptionManagement/SubscriptionManagementStyled.js, src/containers/PlanDetails/PlanDetails.component.js, src/redux/innerPopupReducer.js, src/translations/en/translations.json
=> Add resume plan option

src/components/SubscriptionSwitchesList/SubscriptionSwitchesList.js
https://cleeng.atlassian.net/browse/MSSDK-1311
=> MSSDK-1311 [P3] FIX client exception from NFL

src/redux/finalizeAddPaymentDetailsSlice.js
Add payment details request was failing in case of redirection because finalizePaymentDetailsSlice was not accepting the payment method Id param
=> fix add payment details in case of redirect

src/components/SwitchPlanPopup/SwitchPlanPopup.js
Fix the prices that are displayed in the subscription upgrade downgrade confirmation screen
Replace the nextPaymentPrice with price when its needed
=> Fix prices in confirmation screen

README.md, src/components/Adyen/Adyen.js
https://cleeng.atlassian.net/browse/MSSDK-1316
=> MSSDK-1316 Add option to adjust GooglePay button appearance

README.md, src/components/Adyen/Adyen.js, src/components/Payment/Payment.js
After agreement with Phuong, we want to always show holder name field for Bancontact Card
- added fields to Adyen Config
- fixed bug when noPaymentMethods error was showing before they were fetched
=> Bancontact card changes

src/components/Adyen/Adyen.js
Simply change of bank copy in MyAccount
=> MSSDK-1390 Change the copy for bank payment methods in my account

src/containers/OfferContainer/OfferContainer.js
Refresh the Purchase component when offerId changes to dynamically change Purchase component view.
Just add offerIdProp in the useEffect array
not needed
not needed
not needed
=> Update Purchase component on offerId prop change

.github/workflows/call-publish.yml, .github/workflows/react-16-release.yml
Add workflow to be able to manually publish React-16 temporary package 
- add `react-16-release` workflow
- add option to change branch in `call-publish`
=> add workflow for react 16 package

.github/workflows/call-publish.yml
Fix version of react-16 package
=> Fix version of react-16 package

.github/workflows/on-pull-request.yml
Features packages were build always from main branch
- pass branch name to on-publish workflow
=> fix workflow for feature packages

src/components/Payment/DropInSection/DropInSection.js, src/components/Payment/Payment.js
https://cleeng.atlassian.net/browse/MSSDK-1413
Removed if() checking if selected PM is same as which we are selecting now (it was not working correctly), added this if() to PayPal (normal DropIn works correctly without this if - orders is not created when we are selecting same PM over and over)
=> [MSSDK-1413] P3 - BroadwayHD - Price error in checkout component

.github/workflows/on-pull-request.yml, src/containers/Subscriptions/Subscriptions.component.js
Subscriptions component was failing on load.
- fix how offers are get from the API
- prevent fail when there are no errors
n/a
n/a
n/a
=> MSSDK-1415 fix subscriptions component

README.md
Add small information about rtl support
Add small information about rtl support
-
-
-
=> Add small information about rtl support

src/util/planHelper.js
Fix app fail when there are seasonal offers as switch options
- add proper mapping to planHelper
=> fix switches list if there are seasonal offers

src/util/fetchHelper.js
Add `X-Requested-By` header in the requests to indentify requests from mediastore-sdk library
Add header in the fetch helpers
-
-
The value passed in the X-Requested-By will have a specified format: `mediastore-sdk@version` where version is the semver version like (4.1.0).
=> Add X-Requested-By header

src/components/CurrentPlan/CurrentPlan.js, src/components/SubscriptionSwitchesList/SubscriptionSwitchesList.js
Fix error handling after the TS merge to main 
- errors default value was changes to `null`. These are following up changes
=> fix current plan and subscriptionSwitchesList - error handling

src/components/OfferCheckoutCard/OfferCheckoutCard.tsx
https://cleeng.atlassian.net/browse/MSSDK-1469
=> [MSSDK-1469] Trial banner is not hidden when the coupon is applied and removes trial from offer.

.husky/verify_branch_name, package.json
Add branch verification pre-commit hook
-
-
-
`chmod +x .husky/verify_branch_name` command required to add permissions
=> Add branch verification pre-commit hook

README.md, src/components/Payment/Payment.tsx, src/services/auth.js, src/util/appConfigHelper.js, src/util/eventDispatcher.js, src/util/fetchHelper.js
https://cleeng.atlassian.net/browse/MSSDK-1391
=> [MSSDK-1391] Emit event when the user should be logout

README.md, src/components/UpdateSubscription/Unsubscribe.js
https://cleeng.atlassian.net/browse/MSSDK-1509
=> [MSSDK-1509] NFL - Cancellation Survey

src/components/Adyen/Adyen.js, src/components/Payment/Payment.tsx, src/util/appConfigHelper.js, src/util/paymentMethodHelper.js
=> test/MSSDK-external: release-5-1-1

src/components/Adyen/Adyen.js
https://cleeng.atlassian.net/browse/MSSDK-1519
=> [MSSDK-1519] Fix bancontact card checkbox

src/components/CheckoutPriceBox/CheckoutPriceBox.js, src/components/CheckoutPriceBox/CheckoutPriceBoxStyled.js, src/components/CouponInput/CouponInput.tsx, src/components/CouponInput/CouponInput.types.ts, src/components/Offer/Offer.tsx, src/redux/orderSlice.ts, src/redux/types/orderSlice.types.ts
There has been a reported issue regarding the positioning of the `CouponNote `text, which appears to be rendering too closely to the upper text within the `CheckoutPriceBox`. 
Additionally, a request has been made to remove the fade-away effect from `CouponInput` and add **auto-apply** mechanics to the **VIP Checkout**
- Removed the 'absolute position' styling and refactored the relevant `CheckoutPriceBox` so that the `CouponNote` is displayed using Flexbox.
- Removed the div inside of the `<ul>` to address the a11y issues
- Removed the 'fade-away' mechanics from the `CouponInput `and replaced it with  a new state to manage the coupon message
- Added `couponCode` to the order state structure and applied changes in the `Offer` and `CouponInput` components to handle auto-application
VIP …
=> fix/MSSDK-1522: fix coupon note display

src/components/OfferCheckoutCard/OfferCheckoutCard.tsx, src/util/paymentMethodHelper.js
[MSSDK-1525](https://cleeng.atlassian.net/jira/software/c/projects/MSSDK/boards/142?modal=detail&selectedIssue=MSSDK-1525)
[MSSDK-1525]: https://cleeng.atlassian.net/browse/MSSDK-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/MSSDK-1525: base price in Adyen checkboxes

src/components/Adyen/Adyen.js, src/components/Payment/Payment.tsx, src/redux/publisherConfigSlice.ts, src/redux/types/publisherConfigSlice.types.ts, src/util/appConfigHelper.js, src/util/paymentMethodHelper.js
- add new `Config.setHiddenPaymentMethods` function to hide some of the payment methods by their paymentMethodIds
=> feat/MSSDK-1530: Add setHiddenPaymentMethods function

src/components/Consents/Consents.js
https://cleeng.atlassian.net/browse/MSSDK-1539
=> fix/MSSDK-1539: add checking consents after fetching them

src/components/CheckoutPriceBox/CheckoutPriceBox.js, src/components/CheckoutPriceBox/CheckoutPriceBox.test.js
hide coupon note for unlimited: when period === 'year' && discountedPeriods === 999
=> feat/MSSDK-1538: hide coupon note

src/components/CheckoutPriceBox/CheckoutPriceBox.js, src/translations/en/translations.json
Change "Total" text to "Today's total"
Update in the component and in the translations.json file
=> feat/MSSDK-1576: Change total text in checkout

src/components/InnerPopupWrapper/InnerPopupWrapperStyled.js
Fix the scrolling popups problem
Remove the min-heiight value
=> fix/MSSDK-988: Unset the problematic min-height

src/components/MyAccountInput/MyAccountInput.js, src/components/MyAccountInput/MyAccountInputStyled.js, src/components/ProfileDetails/ProfileDetails.js, src/containers/UpdateProfile/UpdateProfile.component.js
https://cleeng.atlassian.net/browse/MSSDK-912
- Added asterisk when input is required
- It is now not possible to save form when any required input is not filled
=> fix/MSSDK-912: It is possible to delete some required fields from the form of UpdateProfile from MyAccount

src/components/CheckoutPriceBox/CheckoutPriceBox.js, src/components/CheckoutPriceBox/CheckoutPriceBox.test.js, src/translations/en/translations.json
change coupon discount copy in offer in trial
=> fix/MSSDK-1556: change coupon discount copy in offer in trial

src/components/Header/HeaderStyled.js, src/styles/variables.js
`LogoUrl` provided in `Config.setTheme()` is not working
=> fix/MSSDK-1608: fix usage of logoUrl in setTheme

src/components/ThankYouPage/ThankYouPage.js
To make it possible to locate elements when writing E2E tests, the QA Team has asked us to add ID attributes to specific elements in the 'ThankYouPage' component.
New attributes have been added to the "Thank You" title and the two paragraphs that follow.
=> chore/MSSDK-1607: add ids as locators for testing

src/components/Transactions/Transactions.tsx, src/util/paymentMethodHelper.js
=> fix/MSSDK-1617: fix transactions render when Logo is undefined

README.md, src/components/PlanDetailsPopupManager/PlanDetailsPopupManager.tsx, src/components/PlanDetailsPopupManager/PlanDetailsPopupManager.types.ts, src/components/UpdateSubscription/Unsubscribe.tsx, src/components/UpdateSubscription/Unsubscribe.types.ts, src/components/UpdateSubscription/UpdateSubscription.js, src/containers/MyAccount/MyAccount.component.js, src/containers/PlanDetails/PlanDetails.tsx, src/containers/PlanDetails/PlanDetails.types.ts, src/containers/Subscriptions/Subscriptions.component.js
We want to give option to turn off Cancellation Journey flow
Added `skipAvailableFreeExtensionStep` prop that can be used with following components:
`MyAccount`, `Subscriptions`, `PlanDetails`
=> feat/MSSDK-1634: On / Off switch for Cancellation Journeys

src/components/LoginPage/LoginForm.js, src/translations/en/translations.json
=> fix/MSSDK-1590: Fix typo

src/components/UpdatePaymentDetailsPopup/UpdatePaymentDetailsPopup.js, src/translations/en/translations.json
Change back button text in `UpdatePaymentDetails` popup from `Cancel` to `Back to Payment Details`
=> Fix/MSSDK-1309: Bound payment bugs

src/api/Order/createOrder.ts, src/components/DeliveryDetails/DeliveryDetails.tsx, src/containers/OfferContainer/OfferContainer.tsx, src/redux/orderSlice.ts
At the moment initial order is created without buyAsAGift property, then this order is updated with buyAsAGift: true
The goal of this task is to create initial order with buyAsAGift: true property when user already has access to certain offer , without the need to update it.
=> feat/MSSDK-1623: When user has access to giftable offer, create initial order with buyAsAGift: true

src/util/environmentHelper.js
=> feat/MSSDK-1665: add staging2 env

README.md, src/components/Payment/Payment.tsx, src/components/Popup/Popup.js
Missing OfferID in response for event MSSDK:purchase-successful when using coupon
=> Fix/MSSDK-1676: P3 - Missing OfferID in response for event MSSDK:purchase-successful when using coupon

package.json, src/components/Consents/Consents.test.tsx, src/components/CouponInput/CouponInput.test.tsx, src/components/GracePeriodError/GracePeriodError.test.tsx, src/components/OfferMyAccountCard/OfferMyAccountCard.tsx, src/components/PaymentCard/PaymentCard.types.ts, src/containers/PlanDetails/PlanDetails.tsx, src/redux/types/planDetailsSlice.types.ts, src/util/planDetailsMock.ts, tsconfig.json
Added TypeScript checks to pre-commit hook so we can get even bigger certainty in our changes
=> chore/MSSDK-1687: add typescript checks to pre-commit hook

src/components/ErrorPage/ErrorPage.tsx, src/components/ErrorPage/ErrorPage.types.ts, src/components/OfferCheckoutCard/OfferDescription/OfferDescription.tsx, src/containers/OfferContainer/OfferContainer.tsx, src/redux/types/publisherConfigSlice.types.ts, src/translations/en/translations.json
Use new payment gateway for free purchases without payment details
Added new `free-offer` payment gateway
=> feat/MSSDK-1632: Update select payment method settings with that gateway for free purchases without payment details

src/util/planHelper.ts
=> feat/MSSDK-1683: Add thai baht

src/components/FreeOffer/FreeOffer.tsx, src/components/FreeOffer/FreeOfferStyled.ts
Add support of displaying description for the free offer
=> feat/MSSDK-1520: Add offer description and icons to free offer

src/util/environmentHelper.js
replace staging with new staging
=> update staging url

src/components/CheckoutPriceBox/CheckoutPriceBox.tsx, src/translations/en/translations.json
Added `Promotional pricing applied` translation to `translations.json` file
=> feat/MSSDK-1751: P3 - Translations missing in components - review document

package.json
A script for running the dev functionality for Windows-based machines.
=> chore/MSSDK-1696: windows dev script

.github/workflows/call-publish.yml, .github/workflows/react-16-restricted-release.yml
A GitHub Action for publishing private packages for React 16 testing
=> chore/MSSDK-1696: restricted react 16 package release script for github actions

.github/workflows/react-16-restricted-release.yml
Clean up the unused inputs section
=> feat/MSSDK-1777: clean up the unused inputs section

package.json, pnpm-lock.yaml
Downgrade testing library for react to support react 16
=> chore/MSSDK-1791: downgrade testing library for react to support react 16

.github/workflows/call-publish.yml
=> feat/MSSDK-1800: Update pnpm/action-setup from v2 to v4

src/components/ThankYouPage/ThankYouPage.jsx
Removed opening `MyAccount` component in new cart from `ThankYouPage`
=> feat/MSSDK-1772: remove opening MyAccount in new cart

src/components/Checkout/Checkout.jsx, src/components/Price/Price.tsx, src/containers/OfferContainer/OfferContainer.tsx, src/containers/OfferContainer/OfferContainer.types.ts, src/scripts/CleengComponent.js, src/scripts/cleeng.js, src/scripts/constants.js, src/scripts/constants.ts
clear coupon code via URL
fix discount percentage rounding
=> feat/MSSDK-1812: clear coupon code via URL; fix discount percentage rounding

src/components/ThankYouPage/ThankYouPage.jsx, src/util/hostedComponentsHelper.ts, vite.config.ts
To ensure correct operation of navigation within customers' application, we need the embedded versions of our MSSDK components to support making their parents navigate to specified URLs.
=> feat/MSSDK-1826: Handle parent redirects from embedded components' level

src/scripts/CleengComponent.js
Remove cleeng node util for cleeng script
=> feat/MSSDK-1869: remove cleeng node util for cleeng script

.env
update cloudfront distribution domain url
=> feat/MSSDK-1837: update cloudfront distribution domain url

src/package.ts
Improve Sentry initialization condition - init only for sandbox and prod
=> feat/MSSDK-1916: Improve Sentry initialization condition - init only for sandbox and prod

src/package.ts
=> feat/MSSDK-1925: pause Sentry integration

.github/workflows/call-publish.yml, .github/workflows/on-pull-request.yml, .github/workflows/on-release.yml, .github/workflows/react-16-release.yml, .github/workflows/react-16-restricted-release.yml, package.json, pnpm-lock.yaml, src/package.ts, vite.config.ts
Clean up Sentry integration from MSSDK
=> feat/MSSDK-1954: Clean up Sentry integration from MSSDK

src/components/CheckoutPriceBox/CheckoutPriceBoxStyled.tsx, src/components/MyAccountUserInfo/MyAccountUserInfoStyled.js, src/components/OfferCheckoutCard/OfferCheckoutCardStyled.ts, src/components/OfferMyAccountCard/OfferMyAccountCard.tsx, src/components/OfferMyAccountCard/OfferMyAccountCardStyled.ts, src/components/OfferSwitchCard/OfferSwitchCardStyled.ts, src/components/Price/PriceStyled.tsx, src/styles/variables.js, src/translations/en/translations.json, src/util/planHelper.ts
Added specific copy for paused offer with new date format
=> feat/MSSDK-1957: Pause Billing - updating My Account Copy

.github/workflows/call-publish.yml, package.json
Restore proper package's development version
=> chore/MSSDK-1983: Restore proper package's development version

src/components/LoginPage/LoginStyled.js, src/components/RegisterPage/RegisterForm.tsx, src/translations/en/translations.json
show error message when email verification fails during account registration
=> feat/MSSDK-2017: show error message when email verification fails during account registration

README.md
To ensure a seamless developer experience for users of our library, it is necessary to provide clear guidance on configuring the PNPM package manager when installing dependencies. This update will help developers avoid potential issues caused by hoisting behavior, enabling them to set up the library correctly with minimal troubleshooting. By adding these instructions, we aim to improve usability and adoption of our library.
Added instuctions to README.md
=> feat/MSSDK-2045: Add pnpm shamefully-hoist=true instruction to readme

src/hooks/__tests__/useCaptchaVerification.test.ts, src/hooks/useCaptchaVerification.ts
=> [Fix/MSSDK-2112]: Fix behaviour if challange called

src/api/Customer/getOfferDetails.ts
=> [chore/MSSDK-2118]: Rewrite to TS and add JWT to the requset headers

package.json
dev performance improvement: kill the publish-dev processes in the queue when saving multiple times
=> chore/MSSDK-1749: dev performance improvement: kill the publish-dev processes in the queue when saving multiple times

.github/workflows/call-publish.yml, .github/workflows/finalize-release.yml, .github/workflows/release-candidate-pull-request-check.yml
=> chore/MSSDK-2155: add Cleeng pushbot for automated backmerges handling

.github/workflows/call-publish.yml, .github/workflows/finalize-release.yml, .github/workflows/release-candidate-pull-request-check.yml
* chore/MSSDK-2155: add Cleeng pushbot for automated backmerges handling
* chore/MSSDK-2155: remove excessive env config
=> chore/MSSDK-2155: add Cleeng pushbot for automated backmerges handling (#473)

.github/release-drafter.yml
=> chore/MSSDK-2155: fix the release draft full changelog link

src/util/appConfigHelper.js
allow using custom origins for translations
=> chore/MSSDK-1883: allow using custom origins for translations

.github/release-drafter.yml
=> chore/MSSDK-2177: fix the version comparison string

README.md
update readme to reflect the default setting of billingAddressRequired prop for Adyen configuration
=> docs/MSSDK-2153: update readme to reflect the default setting of billingAddressRequired prop for Adyen configuration

src/components/UpdateSubscription/components/Survey.tsx
fix wrong translation key used for the unsubscribe survey title
=> fix/MSSDK-2357: fix wrong translation key used for the unsubscribe survey title

src/components/CheckoutPriceBox/CheckoutPriceBox.tsx, src/components/OfferCheckoutCard/OfferCheckoutCard.tsx, src/components/OfferMyAccountCard/OfferMyAccountCard.tsx, src/components/OfferSwitchCard/OfferSwitchCard.tsx, src/components/SwitchPlanPopup/SwitchPlanPopup.jsx, src/components/ThankYouPage/ThankYouPage.jsx, src/components/UpdateSubscription/Resubscribe.jsx, src/util/paymentMethodHelper.js, src/util/planHelper.ts
=> feat/MSSDK-2456: add support to MYR currency

src/components/SwitchPlanPopup/SwitchPlanPopup.jsx
=> fix/MSSDK-2467: fix currencies in the switch popup

src/components/DeliveryDetails/RecipientForm/helpers.ts
Fix showing correct timezone `deliveryDate` and `deliveryTime` in gift's edit view
=> feat/MSSDK-2460: fix showing delivery date and time in correct timezone
