Cleeng/mediastore-sdk

.github/workflows/release.yml
Same deal as here: https://github.com/Cleeng/mediastore-sdk/pull/41
we need to bump the permissions because we've switched to read-only in all repos, so additional claims need to be added explicitly.
=> Add contents:write permissions to release workflow

src/components/SwitchPlanPopup/SwitchPlanPopupStyled.js
- Add padding to fix the labels spacing
- Add margin to make a space between labels and the header
=> Fix switch plan popup spacing

src/components/Adyen/Adyen.js, src/components/Adyen/AdyenStyled.js, src/components/Payment/DropInSection/DropInSection.js, src/components/Payment/DropInSection/DropInSectionStyled.js, src/components/Payment/Payment.js
- add 'Purchase using' header
- improve Adyen font styles
- fadeout PayPal when payment from Adyen started
- hide PayPal when DropIn is re-rendering
=> adjust styles

src/components/Card/CardStyled.js, src/components/MyAccountError/MyAccountErrorStyled.js, src/components/PaymentCard/PaymentCard.js, src/components/PaymentCard/PaymentCardStyled.js, src/components/PaymentMethod/PaymentMethodStyled.js
- reduced margin in Card component from 39px to 32px
- centered icons in MyAccountError
- moved PayPal holderName under the method name and changed its styling
- changed breakpoint from smallest to medium in PaymentCard
- changed breakpoint from 900px to 1550px in PaymentMethod
[MSSDK-1296]: https://cleeng.atlassian.net/browse/MSSDK-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MSSDK-1296 fix payment details styling

src/api/Offers/getOffers.js, src/components/SubscriptionSwitchesList/SubscriptionSwitchesList.js, src/containers/SubscriptionSwitches/SubscriptionSwitches.component.js
- add `pageLimit=100` for **getOffers** request, because the default value is 15 and that was causing problems in publisher with more than 15 offers
- add **getOffers** request in `SubscriptionSwitches` component to make it work also in that component if is used separetely
=> Fix subscription switches pause feature

src/components/OfferCheckoutCard/OfferCheckoutCard.js, src/components/OfferCheckoutCard/OfferCheckoutCardStyled.js, src/translations/en/translations.json
**Dynamic trial label on the checkout page**
- added generateTrialBadgeDescription() function to handle days and periods variants with dynamic translation
- updated translations.json file with keys and values accordingly
- changed label's min- and max-width values
[MSSDK-1302]: https://cleeng.atlassian.net/browse/MSSDK-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MSSDK-1302-dynamic-trial-label

src/components/CheckoutPriceBox/CheckoutPriceBox.js
Tax annotation in  is now visible in all cases, even if its value shows 0.  In case of free offers, tax segment is always struck through. 
Previously, there was no tax row displayed when its value was equal to 0, what might have led to a confusion for non-EU customers when they were presented with inconsistent _incl._ - _excl._  tax information in `Checkout`
Conditional rendering for tax row has been removed leaving only a ternary operator determining if the offer is free or not.
=> MSSDK-1314 - fix tax annotation display

src/services/auth.js
There has been a client report of user data leaking between sessions
Remove more data from localStorage & store on user logout:
- customer email, 
- customer ID,
-  environment, 
-  publisher ID
=> remove customer-identifying data on logout

src/components/Capture/CaptureForm/CaptureFormStyled.js, src/components/Capture/CaptureStyled.js
The capture component's inputs were getting squished on smaller displays
Modified styling for the component:
- reduced content padding to 5% on displays < 1024px wide,
- flipped the input wrapper back to `display: block` on displays < 768px wide so input siblings drop down
Before:
After:
=> update styling for smaller displays in the Capture component

README.md, src/components/Adyen/Adyen.js, src/components/SkeletonWrapper/SkeletonWrapper.js
Next.js doesn't allow third-party CSS imports from `node_modules` (as reported in #197) and throws the [css-npm](https://nextjs.org/docs/messages/css-npm) error while importing our library.
Removed the imports in the offending components:
- `Adyen.js`
- `SkeletonWrapper.js`
And updated the README to reflect the changes required by this.
=> remove node_modules CSS imports

src/components/Adyen/AdyenStyled.js, src/components/Checkbox/CheckboxStyled.js, src/components/CouponInput/CouponInputStyled.js, src/components/MyAccountInput/MyAccountInputStyled.js, src/components/MyAccountMenu/MyAccountMenuStyled.js, src/components/OfferCard/OfferCard.js, src/components/OfferCard/OfferCardStyled.js, src/components/OfferCheckoutCard/OfferCheckoutCardStyled.js, src/components/PauseSubscriptionPopup/PauseSubscriptionPopupStyled.js, src/components/Payment/DropInSection/DropInSectionStyled.js, src/components/PaymentCard/PaymentCardStyled.js, src/components/ResumeSubscriptionPopup/ResumeSubscriptionPopupStyled.js, src/components/SubscriptionIcon/SubscriptionIconStyled.js, src/components/SwitchPlanPopup/SwitchPlanPopupStyled.js, src/components/Transactions/TransactionsStyled.js, src/components/UpdatePaymentDetailsPopup/UpdatePaymentDetailsPopupStyled.js, src/styles/RTLHelper.js
Add support for dir="rtl" attribute in mediastore-sdk library
- adding new helper `isRTL()` that will return true if dir="rtl" is set in the document
- based on the document.dir value add some style alignment (margins, paddings)
=> [MSSDK-1385] Add right-to-left support in mediastore-sdk

src/components/Input/InputStyled.js
Fix the input labels and error messages to work also on the rtl direction
Only small changes in the InputStyled.js
=> Fix rtl styles in the input element

package.json
Types packages are used only for development so should be placed in devDependecies
- move types/react-redux from dependencies to devdependencies
=> move types/react-redux to devDep

src/api/Offers/getOffer.ts, src/api/index.js, src/containers/OfferContainer/OfferContainer.tsx, src/redux/offerSlice.ts, src/redux/types/offerSlice.types.ts, src/types/OfferType.types.ts, src/types/OfferV2.types.ts, src/types/Price.types.ts
Add call to the `v2/offers/{offerId}` in the Purchase component
- add new `getOffer` api method
- add `offerV2` entry in the Redux not to override the previous offer details
- add `createAsyncThunk` in the `offerSlice.ts` that will menage offer request
- dispatch `fetchOfferV2` method in the OfferContainer component
- add separate `types/` folder to store some common types like `Price`, `OfferV2` etc.
=> Add get offer V2

src/components/OfferCheckoutCard/OfferCheckoutCard.tsx, src/util/calculateGrossPriceForFreeOffer.js
For some specific cases the wrong price rounding is applied in the checkout. In this fix, for cases where tax rate is 0 I return the net price as gross price.
- return net price when tax rate is 0
Added in the ticket.
=> fix/MSSDK-1511: calculate gross price only when tax rate is not 0

src/components/OfferCheckoutCard/OfferCheckoutCard.tsx
Addressing a bug in the `OfferCheckoutCard`. If the user applied a coupon to the seasonal subscription with an ongoing promotional price, the copy incorrectly suggested that after the promotional period, they would still incur the discounted price, not the base price.
- added a ternary operator to correctly display the base price for coupons applied to the seasonal offers
=> fix/MSSDK-1529: correct base price in the offer description

src/containers/OfferContainer/OfferContainer.tsx, src/redux/orderSlice.ts
During the process of checkout/purchase we are storing the orderId in the local storage. If the user after some time enter again the checkout/purchase we are showing that old order. There is a possibility that the order is invalid or expired and that is causing the 422 /sessions problem.
To remove that problem we made some changes to wait with the /sessions call as long as getOrder/createOrder is taking place. After succesful getting order or order creation the sessions request will be called. 
- add async/await to make sure that we will be wainting for the end of the getOrder/createOrder
- because the unsuccesful getOrder is always followed by the createOrder we wont change the loading to false (just to make sure that, in that moment, the Offer component with the session call wont be …
=> feat/MSSDK-1550: Fix session endpoint call

src/i18NextInit.js
Based on the i18next docs https://www.i18next.com/overview/configuration-options#languages-namespaces-resources we decided to remove the fallback language to remove a call for that one on the client side.
Set a fallbackLng property to false
Before:
After:
=> feat/MSSDK-1561: Remove the fallback language from i18next init

src/components/Adyen/Adyen.js
When the user enter the coupon code (100% for example) we are rendering the payment component because the discount was applied. After the coupon application if the user change the coupon code (50% for example) the Adyen component still renders the previous state (Confirm preauthorisation or the first price in the CTA button)
Add `totalPrice` from order object to the `useEffect` dependencies array to re-render the Adyen component when the price change after couponCode reapplication
=> fix/MSSDK-1560: Rerender payment component when totalPrice change

src/components/Adyen/Adyen.js
Fix of Adyen thrown error when trying to use Purchase or Checkout. It is related to checking legal payment checkbox before payment.
`Component` object returned from Adyen `onSubmit` was used for checking it but now it can return `null`.  `State` object from Adyen cannot be used because we can use Visa card in Bancontact Card window, so it will return `type: scheme` and `brand: visa`. I will not know that it is Bancontact Card window.
Used `selectedPaymentMethod` from redux to check if Bancontact Card is opened.
=> fix/MSSDK-1618: Adyen throws error when trying to use Purchase or Checkout 

src/components/Adyen/Adyen.js
There was a problem that Adyen dropin component was recreated after the changes of the paymentMethod (when paymentMethodFee was different -> totalPrice was different).
- we replaced the totalPrice in the useEffect by the discountAmount so the Adyen dropin will be recreated only if the coupon change (this will change the discountAmount, we dont have info about the discount in % so we have to operate on the prices)
=> fix/MSSDK-1629: Replace the totalPrice changes by discountAmount

src/containers/OfferContainer/OfferContainer.tsx
Issue:
Previously, when a free offer was purchased, the orderResponse object sometimes lacked a paymentMethodId. This absence caused an error in our system.
Solution:
The code has been updated to check for the paymentMethodId in the orderResponse. If paymentMethodId is falsy, an API call is made to retrieve this ID. This ensures that the process completes successfully even when the initial paymentMethodId is missing.
This modification ensures that orders for free offers are processed correctly without encountering errors related to missing paymentMethodId.
=> fix/MSSDK-1537: fix no payment method id when buying free offer

src/components/Adyen/AdyenStyled.js, src/components/Payment/PayPal/PayPalStyled.ts
When user enters a valid credit card but forget to submit the consent box, the error is too subtle.
Changed consent text color when error is present
=> feat/MSSDK-1633: When submitting payment form - error too subtle (difficult to spot)

README.md, src/api/Auth/resetPassword.js, src/components/EditPassword/EditPassword.tsx, src/components/PasswordReset/PasswordReset.js, src/redux/publisherConfigSlice.ts, src/redux/types/publisherConfigSlice.types.ts, src/util/appConfigHelper.js
Currently, when customer tries to change the password through the MSSDK Components, he/she is redirected from the email to the Cleeng reset password page.
We could add an option to MSSDK components, so the publisher will be able to create his own reset password page.
Added `Config.setResetUrl()` method to set custom reset password url. This url will be sent to user's email with additional parameters.
=> feat/MSSDK-901: Add option to use custom reset password page in Components

README.md, src/components/Checkout/Checkout.js, src/components/CheckoutPriceBox/CheckoutPriceBox.js, src/components/Offer/Offer.tsx, src/components/Offer/Offer.types.ts, src/containers/OfferContainer/OfferContainer.tsx, src/containers/OfferContainer/OfferContainer.types.ts
Some publishers are not using gifting feature and would like to hide Redeem here button from in Checkout. Add prop to make it possible.
Added `hideRedeemButton` prop in `Checkout `component
=> feat/MSSDK-1675: Add option to hide redeem gift button in Checkout

src/util/calculateGrossPriceForFreeOffer.ts, src/util/calculateTaxValueForFreeOffer.ts
`grossPrice` does not get a proper formatting - displayed price is equal to EUR 9.98 when it should be 9.99
used `Math.ceil()` function to round price up
=> fix/MSSDK-1512: grossPrice calculation does not cover edge-cases properly 

src/components/Capture/CaptureForm/CaptureForm.js
Capture after register in Checkout component does not show error for names fields
=> fix/MSSDK-1670: Capture after register in Checkout component does not show error for names fields

package-lock.json, package.json
With these changes, we need to just run `npm run dev` inside this repo and the app will automatically refresh and reload after making any changes.
The changes I've done here also assume that you have the `mediastore-sdk-demo-2024` repo checked out as a sibling folder to this repository - just as in the README.md of the `mediastore-sdk-demo-2024`.
To save some CPU power, I specifically excluded the recompilation script if the changes have been done to either types files or unit tests files.
Please let me know if you think of any more files we could exclude. All feedback welcome!
=> chore/MSSDK-1691: dev script to automatically recompile, publish and refresh app after making any changes

src/components/AdditionalProfileInfo/AdditionalProfileInfo.js, src/components/Adyen/Adyen.js, src/components/CheckboxLegacy/CheckboxLegacy.js, src/components/CheckboxLegacy/CheckboxLegacy.test.js, src/components/CheckboxLegacy/CheckboxLegacyStyled.js, src/components/CheckoutConsents/CheckoutConsents.js, src/components/CheckoutConsents/CheckoutConsentsStyled.js, src/components/Consents/Consents.test.tsx, src/components/Consents/Consents.tsx, src/components/Payment/PayPal/PayPal.tsx, src/components/UpdateSubscription/components/Survey.tsx
After checking it looks like it’s frontend issue with checking the checkbox state. Checkbox state value returns `undefined` and blocks further payment processing. Fix checking of checkbox state, find more bulletproof way to check it.
Used new `Checkbox` component in `PayPal.tsx` and added invisible input element to `CheckboxLegacy` for Adyen payment methods - to change checking state of checkbox to `checked` value of input element
=> fix/MSSDK-1746: P2 TOD 2.0 - payment can't be finalized 

src/package.ts
There was an error in one of our clients that `ReferenceError: window is not defined` so to make sure that it wont happen again we add check if window is available before calling `onload`.
- add if statement in the `package.ts`
=> fix/MSSDK-1752: Make sure that window is available before onload call

package.json, pnpm-lock.yaml
In order to enable the usage of the preferred version of iDeal 2.0 payment method, we need to use latest (5.66.1) version of the Adyen Drop-in.
Updated `adyen-web` package to 5.66.1 version
=> feat/MSSDK-1788: Update drop-in to the latest version to enable iDEAL 2.0

src/components/Transactions/TransactionsStyled.ts
Fix PayPal icon width
Change min-width to width
=> fix/MSSDK-1829: Set the width of the Paypal icon

src/components/ProfileDetails/ProfileDetails.jsx
User is unable to save profile details form when date of birth field is not present with specific capture settings
Changed destructuring of `enabled` and `required` properties to avoid destructuring `null` field
=> fix/MSSDK-1754: Unable to save profile details form when date of birth field is not present

src/scripts/CleengComponent.js, src/scripts/cleeng.js, src/scripts/constants.js
Configure method now accepts JWT and refresh token.
It uses postMessage API to communicate these values to the hosted MSSDK.
=> feat/MSSDK-1831: extend the configure method of Cleeng script to enable external SSO

src/assets/images/checkboxCheckmark.svg, src/components/AdditionalProfileInfo/AdditionalProfileInfo.jsx, src/components/Adyen/Adyen.jsx, src/components/Adyen/AdyenStyled.js, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/CheckboxStyled.tsx, src/components/CheckboxLegacy/CheckboxLegacy.jsx, src/components/CheckboxLegacy/CheckboxLegacyStyled.js, src/components/MyAccountConsents/MyAccountConsents.jsx, src/components/MyAccountConsents/MyAccountConsentsStyled.js, src/components/MyAccountError/MyAccountErrorStyled.ts, src/components/Password/Password.jsx, src/components/Payment/PayPal/PayPal.tsx, src/components/Payment/PayPal/PayPalStyled.ts, src/components/PaymentCard/PaymentCardStyled.ts, src/components/ProfileDetails/ProfileDetails.jsx, src/containers/SubscriptionSwitches/SubscriptionSwitches.component.jsx
Some colors are inconsistent after changing theme. For example if client uses dark theme and changes font to white, some texts may not be visible. When client changes main color in low code settings to orange, some buttons or checkboxes are still green.
Changed checkboxes behavior, checkbox in `Adyen` behaves correct now to clicking and using space key. Other checkboxes from now are using `ConfirmColor` as background when clicked. Fixed invisible fonts and buttons which used `FontColor` as background
=> feat/MSSDK-1861 Fix styling inconsistencies after using setTheme colors from backend 

src/util/regexConstants.ts, src/util/validators.ts
Using emails with `-` sign in domain part shows `incorrect email` error in `PasswordReset` component
Used popular email regex to accept all correct email formats, also used in during registering phase
=> fix/MSSDK-1860: P3 - All Publishers - Reset Password Inconsistency

src/scripts/index.js, src/util/hostedComponentsHelper.ts
Fix  `window is not defined` error that appears during Next JS server side rendering
=> P3 - NFL - Unable to upgrade to 5.5.3 from 5.4.4

src/components/Price/Price.tsx
Offer price once coupon is applied shows the base offer instead of localized offer.
Used the localized offer prize for strikethrough price and discount % calculation.
Used the price of the converted currency for strikethrough price and discount % calculation.
=> fix/MSSDK-1943: P3 - VBTV - Localized offers with wrong checkout price when applying coupon

src/components/Adyen/Adyen.jsx, src/components/Offer/Offer.tsx
PayPal payment option becomes unclickable after returning from the PayPal page or stopping the PayPal redirection from loading
Added page refresh if page was loaded from `bfcache`
=> fix/MSSDK-1942: P3 - TODtv - PayPal payment method becomes unselectable

README.md, package.json, src/styles/msdFont.css
Fix the export path of the MSSDK font CSS
Update readme about the proper way of importing the fonts
=> fix/MSSDK-1961: Fix the export path of the MSSDK font CSS; update readme about the proper way of importing the fonts

package.json, pnpm-lock.yaml
upgrade Vitest to latest version
I recommend installing the Vitest VS code extension for better support within the IDE - it can interactively run the tests, debug the failing ones, etc.
=> feat/MSSDK-2106: upgrade Vitest to latest version

src/components/ProfileDetails/ProfileDetails.jsx
The email address remained unchanged, but the email validation in ProfileDetails throws an error.
`email` field is now not included in request body when it's not updated
=> fix/MSSDK-2117: MyAccount component throws error when saving personal info without editing the e-mail field

src/components/CheckoutPriceBox/CheckoutPriceBox.tsx, src/components/OfferCheckoutCard/OfferCheckoutCard.tsx, src/translations/en/translations.json
After some review from the finance team there was a decision to make one copy for the taxes in checkout 
For the applied tax on the checkout, the term “Applicable tax” should be used universally.
=> feat/MSSDK-2029: Align tax copy in checkout

src/components/RegisterPage/useRegisterForm.ts
=> fix/MSSDK-2133: Fix invalid token error nad small refactor

package.json, pnpm-lock.yaml, src/appRedux/types/publisherConfigSlice.types.ts, src/components/Adyen/Adyen.jsx, src/components/Payment/Payment.tsx, src/components/PaymentDropIn/PaymentDropIn.tsx, src/components/PaymentDropIn/PaymentDropIn.types.ts, src/components/PaymentDropIn/index.ts, src/components/Primer/Primer.tsx, src/components/Primer/index.ts, src/components/UpdatePaymentDetailsPopup/UpdatePaymentDetailsPopup.jsx, src/hooks/usePaymentDropIn.ts, src/hooks/usePaymentDropIn.tsx, src/types/Adyen.types.ts, vite.config.ts
To introduce a `Primer` component similar to the existing `Adyen` component in the project. Import it using lazy loading. The component will import and initialize `@primer-io/checkout-web` but will not be integrated with the backend, resulting in an expected error.
=> feat/MSSDK-2126: Create Primer component without backend integration

.husky/scripts/verify_branch_name, .husky/scripts/verify_commit_message
add missing conventional commits names to commit and branch name verification
=> chore/MSSDK-2108: add missing conventional commits names to commit and branch name verification
